FROM nginx:1.22.1-alpine as build-stage
RUN mkdir /src
WORKDIR /src
COPY ./server/ /src/

FROM nginx:1.22.1-alpine as prod-stage
RUN rm -rf /etc/nginx/conf.d/
COPY --from=build-stage /src/config/nginx.conf  /etc/nginx/conf.d/
RUN rm -rf /home/*
COPY --from=build-stage /src/ /home/
EXPOSE 80